#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=bsskick
PROG=/usr/bin/bsskick
CONFIGURATION=bsskick

start_service() {
        config_load "${CONFIGURATION}"
        local time
        config_get time main time
        procd_open_instance
        procd_set_param command "$PROG" "$time"
        procd_set_param file /etc/config/bsskick
        procd_close_instance
}

reload_service() {
        procd_send_signal $PROG
}
